<a href="https://colab.research.google.com/github/PhonxayMax/PhonxayMax-InsideDeepLearning_Edward_Raff/blob/main/Chapter_2_DataLoader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
class Simple1DRegressionDataset(Dataset):

    def __init__(self, X, y):
        super(Simple1DRegressionDataset, self).__init__()
        self.X = X.reshape(-1,1)
        self.y = y.reshape(-1,1)


    def __getitem__(self, index):
        return torch.tensor(self.X[index,:], dtype=torch.float32), torch.tensor(self.y[index], dtype=torch.float32)

    def __len__(self):
        return self.X.shape[0]

training_loader = DataLoader(Simple1DRegressionDataset(X, y), shuffle=True)

In [13]:
# Example Data
import torch
from torch.utils.data import DataLoader, Dataset

X = torch.linspace(0, 10, 100)  # 100 points between 0 and 10
y = 2 * X + 1  # Simple linear function (y = 2x + 1)


# Create Dataset
dataset = Simple1DRegressionDataset(X, y)
dataset

In [16]:

# Create DataLoader for batching and shuffling
training_loader = DataLoader(dataset, batch_size=10, shuffle=True)

# Fetch a single batch
for inputs, labels in training_loader:
    print("Inputs:", inputs.shape)  # (batch_size, 1)
    print("Labels:", labels.shape)  # (batch_size, 1)
    break  # Print only the first batch
print(inputs)
print(labels)

Inputs: torch.Size([10, 1])
Labels: torch.Size([10, 1])
tensor([[7.6768],
        [7.8788],
        [5.8586],
        [0.7071],
        [7.5758],
        [3.5354],
        [7.3737],
        [4.0404],
        [6.6667],
        [4.3434]])
tensor([[16.3535],
        [16.7576],
        [12.7172],
        [ 2.4141],
        [16.1515],
        [ 8.0707],
        [15.7475],
        [ 9.0808],
        [14.3333],
        [ 9.6869]])


<ipython-input-2-5f3f45851640>:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(self.X[index,:], dtype=torch.float32), torch.tensor(self.y[index], dtype=torch.float32)


In [10]:
import numpy as np
X = np.array([[1], [2], [3], [4], [5]])  # Shape: (5,1)
print(X.dtype)
index = 2
print(X)
print(X[index, :])  # Output: [3] (still 2D, shape (1,))
print(X[index, :].dtype)
print(X[index])     # Output: [3] (same result in this case)


int64
[[1]
 [2]
 [3]
 [4]
 [5]]
[3]
int64
[3]
