<a href="https://colab.research.google.com/github/PhonxayMax/PhonxayMax-InsideDeepLearning_Edward_Raff/blob/main/Chapter_2_DataLoader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch.utils.data import DataLoader, Dataset

In [3]:
class Simple1DRegressionDataset(Dataset):

    def __init__(self, X, y):
        super(Simple1DRegressionDataset, self).__init__()
        self.X = X.reshape(-1,1)
        self.y = y.reshape(-1,1)


    def __getitem__(self, index):
        return torch.tensor(self.X[index,:], dtype=torch.float32), torch.tensor(self.y[index], dtype=torch.float32)

    def __len__(self):
        return self.X.shape[0]

# Copy all code then prompt it down on ChatGPT

##for entire dataset X and y have 100 values but we fetch from this just 10 values from the lines batch_size=10

In [4]:
# Example Data

X = torch.linspace(0, 10, 100)  # 100 points between 0 and 10
y = 2 * X + 1  # Simple linear function (y = 2x + 1)


# Create Dataset
dataset = Simple1DRegressionDataset(X, y)
dataset

In [7]:

# Create DataLoader for batching and shuffling
training_loader = DataLoader(dataset, batch_size=10, shuffle=True)

# Fetch a single batch
for inputs, labels in training_loader:
    print("Inputs:", inputs.shape)  # (batch_size, 1)
    print("Labels:", labels.shape)  # (batch_size, 1)
    print(inputs)
    print(labels)
    #break  # Print only the first batch


Inputs: torch.Size([10, 1])
Labels: torch.Size([10, 1])
tensor([[ 1.2121],
        [ 2.9293],
        [ 5.3535],
        [ 4.0404],
        [ 6.2626],
        [ 0.9091],
        [10.0000],
        [ 4.9495],
        [ 1.1111],
        [ 2.8283]])
tensor([[ 3.4242],
        [ 6.8586],
        [11.7071],
        [ 9.0808],
        [13.5253],
        [ 2.8182],
        [21.0000],
        [10.8990],
        [ 3.2222],
        [ 6.6566]])
Inputs: torch.Size([10, 1])
Labels: torch.Size([10, 1])
tensor([[5.9596],
        [9.3939],
        [9.8990],
        [2.7273],
        [8.6869],
        [5.0505],
        [6.1616],
        [1.9192],
        [1.3131],
        [2.6263]])
tensor([[12.9192],
        [19.7879],
        [20.7980],
        [ 6.4545],
        [18.3737],
        [11.1010],
        [13.3232],
        [ 4.8384],
        [ 3.6263],
        [ 6.2525]])
Inputs: torch.Size([10, 1])
Labels: torch.Size([10, 1])
tensor([[9.6970],
        [2.4242],
        [7.3737],
        [7.9798],
      

<ipython-input-3-8a0cf4ebd8b9>:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(self.X[index,:], dtype=torch.float32), torch.tensor(self.y[index], dtype=torch.float32)


In [ ]:
import numpy as np
X = np.array([[1], [2], [3], [4], [5]])  # Shape: (5,1)
print(X.dtype)
index = 2
print(X)
print(X[index, :])  # Output: [3] (still 2D, shape (1,))
print(X[index, :].dtype)
print(X[index])     # Output: [3] (same result in this case)


int64
[[1]
 [2]
 [3]
 [4]
 [5]]
[3]
int64
[3]
